# Generated by Django 4.2.13 on 2024-06-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="is_free",
        ),
        migrations.AddField(
            model_name="course",
            name="price_status",
            field=models.CharField(
                choices=[("FREE", "Free"), ("PAID", "Paid")],
                default="PAID",
                help_text="Indicates whether the course is available for free or not.",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="discount_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Discount price of the course.",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="regular_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Price of the course.",
                max_digits=6,
            ),
        ),
    ]
