# Generated by Django 4.2.13 on 2024-07-05 08:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0002_remove_course_is_free_course_price_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("content", models.TextField(max_length=1000)),
                ("reviewed_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="whatyoulllearn",
            name="course",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="completion_date",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="feedback",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="is_completed",
        ),
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                through="courses.Enrollment", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="CourseRequirement",
        ),
        migrations.DeleteModel(
            name="WhatYoullLearn",
        ),
        migrations.AddField(
            model_name="coursereview",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="coursereview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
