# Generated by Django 4.2.13 on 2024-06-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELED", "Canceled"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total regular price of courses before any discounts.",
                max_digits=10,
            ),
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
